### ISSUE TITLE
Stacktrace about unicorn and redis

### ISSUE THREAD

**Issue by yippibrian** [repsheet/visualizer#12]
I found the following website that explains how to configure unicorn to work with redis, and it sounds this involves creating a unicorn.conf file or perhaps otherwise redesigning things so the connect happens after the fork:
  https://github.com/mperham/sidekiq/issues/120

When I run the visualizer and send access the repsheet visualizer in a browser, I see the following stack trace in the repsheet_visualizer output.  

[2014-02-17 21:43:19] INFO  WEBrick::HTTPServer#start: pid=10323 port=4567
[2014-02-17 21:43:27] ERROR bad Request-Line `*2'.
appsec-test-small1.snc1 - - [17/Feb/2014:21:43:27 UTC] "*2" 400 296
- ->
Redis::ProtocolError -  Got 'H' as initial reply byte. If you're in a forking environment, such as Unicorn, you need to connect to Redis after forking. :
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:288:in `format_reply'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:275:in `read'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis.rb:426:in `block in exists'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
	/usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
	/usr/local/lib/ruby/gems/1.9.1/gems/redis-3.0.7/lib/redis.rb:425:in `exists'
	/packages/encap/repsheet_visualizer-1.0.0_2014.02.15_19.09/lib/repsheet_visualizer/application/backend.rb:19:in `summary'
	/usr/local/lib/repsheet_visualizer/application/app.rb:71:in `block in <class:App>'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1593:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1593:in `block in compile!'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `[]'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (3 levels) in route!'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:976:in `route_eval'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (2 levels) in route!'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:997:in `block in process_route'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `catch'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `process_route'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:955:in `block in route!'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `each'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `route!'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1067:in `block in dispatch!'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1064:in `dispatch!'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `block in call!'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `call!'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:877:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.2/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.2/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.2/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.2/lib/rack/protection/base.rb:50:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.2/lib/rack/protection/base.rb:50:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.2/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:180:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:2004:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `block in call'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1778:in `synchronize'
	/usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `call'
	/usr/local/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
	/usr/local/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
	/usr/local/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
	/usr/local/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
build1.snc1 - - [17/Feb/2014:21:43:27 UTC] "GET / HTTP/1.1" 500 3874
- -> /

**Comment by munamata** [comment]
Did you ever find a solution to that.?
