### ISSUE TITLE
Marked and whitelisted numbers switched

### ISSUE THREAD

**Issue by Adar** [repsheet/visualizer#18]
Hello,
it seems that for me the numbers of marked and whitelisted IPs is being switched.

![222834091_1704609186883492205](https://cloud.githubusercontent.com/assets/126056/15805112/d8e8a7f0-2b1f-11e6-9257-06bac2bf5985.jpg)

This seems to happen only if there are marked IPs inserted w/o any reason by the CLI tool.

**Comment by abedra** [comment]
Thanks for noting this. I'll get a fix out today.
